# Generated by Django 5.1.3 on 2024-11-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('application_name', models.CharField(max_length=100)),
                ('application_type', models.CharField(choices=[('Social', 'Social'), ('Work', 'Work'), ('Other', 'Other')], max_length=50)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
