# Generated by Django 5.1.3 on 2024-12-01 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0002_storedpassword_delete_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storedpassword',
            old_name='app_name',
            new_name='application_name',
        ),
        migrations.RenameField(
            model_name='storedpassword',
            old_name='app_type',
            new_name='application_type',
        ),
        migrations.RenameField(
            model_name='storedpassword',
            old_name='encrypted_password',
            new_name='password',
        ),
    ]
