# Generated by Django 5.1.3 on 2024-12-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0003_rename_app_name_storedpassword_application_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedpassword',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
