# Generated by Django 5.1.3 on 2024-12-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0004_storedpassword_website_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storedpassword',
            name='application_type',
        ),
        migrations.RemoveField(
            model_name='storedpassword',
            name='website_name',
        ),
        migrations.RemoveField(
            model_name='storedpassword',
            name='website_url',
        ),
        migrations.AddField(
            model_name='storedpassword',
            name='category',
            field=models.CharField(choices=[('Social Media', 'Social Media'), ('Banking', 'Banking'), ('Work', 'Work'), ('Other', 'Other')], default='Other', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storedpassword',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
