# Generated by Django 5.1.3 on 2024-12-06 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0006_alter_storedpassword_user_encryptedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EncryptedFile',
        ),
    ]
